# Generated by Django 3.1.7 on 2021-02-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='titie',
            new_name='title',
        ),
    ]
