# Generated by Django 3.1.7 on 2021-02-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20210222_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works',
            new_name='work',
        ),
    ]
